<?php

namespace LSTATS\RiotBundle\Repository;

/**
 * ChallengerSummonerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChallengerSummonerRepository extends \Doctrine\ORM\EntityRepository
{
}
