<?php

namespace LSTATS\RiotBundle\Repository;

/**
 * ChampionMasteryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampionMasteryRepository extends \Doctrine\ORM\EntityRepository
{
}
