<?php

namespace LSTATS\RiotBundle\Repository;

/**
 * SummonerToRefreshRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SummonerToRefreshRepository extends \Doctrine\ORM\EntityRepository
{
}
