<?php

namespace LSTATS\RiotBundle\Repository;

/**
 * TeamOneGameStatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamOneGameStatRepository extends \Doctrine\ORM\EntityRepository
{
}
